Feature/5 디테일 페이지 구현
juseonghyun/nbc_ContactApp pull request #10
Opened 2024-04-24 10:21 UTC by koreabgj

💻 작업 사항

- 연락처 리스트로부터 전달된 사진, 이름, 전화번호, 이메일 주소, 소속팀 데이터를 intent.getParcelableExtra로 디테일 액티비티 화면에 구현
- 플로팅 버튼 클릭시 다이얼로그 띄우는 로직 구현
- back 버튼은 화면 내부와 디바이스 자체 버튼 2개로 구현

- 메모란 한 줄에 적을 수 있는 글자 수는 최대 10자로 하여 스크롤뷰 사용하게 함
- 스크롤뷰 밖에 back, 메시지, 통화, 플로팅 버튼
을 배치하여 스크롤되지 않게 함
- 플로팅 버튼은 메인 액티비티에 있는 버튼으로 변경 예정

2024-04-24 11:39 UTC, hyezg commented on app/src/main/java/com/example/nbc_sunnyus/model/UserInfo.kt
> +    val image: Int, // 프로필 이미지
마지막에 콤마빼야하지 않나용?!

2024-04-24 11:43 UTC, hyezg approved these changes
확인했습니다! 수고하셨습니다~

2024-04-24 12:05 UTC, koreabgj commented on app/src/main/java/com/example/nbc_sunnyus/model/UserInfo.kt
> +    val image: Int, // 프로필 이미지
에러는 안 나는데 빼는 것이 좋겠죠?

2024-04-24 12:21 UTC, yeonsoo940630 approved these changes
확인했습니다~

2024-04-24 12:54 UTC, yoonchanchoi requested changes
구현하시느라 고생하셨습니다. 리뷰 남깁니다.^^

2024-04-24 12:54 UTC, yoonchanchoi commented on app/build.gradle.kts
> +    id("kotlin-parcelize")
Parcelize로 gradle 설정 잘 해주셨군요👍

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/AndroidManifest.xml
> +        <activity
매니 페스트에 제대로 Activity를 선언 해주셨군요👍

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactDetailActivity.kt
> +    private val userInfo by lazy {
데이터를 받는 부분을 setupData()라는 함수로 빼서 구현 하는 건 어떨 까용?😥

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactDetailActivity.kt
> +        userInfo?.let {
여기 부분도 setupData()에서 함께 묶어 주는 건 어떨까용?😥

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactDetailActivity.kt
> +        binding.btnFloating.setOnClickListener {
2개의 Listener()를 setupListener()에 묶어서 따로 뺀다면 onCreate()에 들어갈 코드가 줄어들게 되고 가독성도 좋아 질 것 같습니다.😅
추가적으로 해당 부분 dialog를 미리 예상하셔서 잘 해주셨어요. 하지만 현재 확실하게 다이얼로그 부분에 코드가 없기 때문에 해당 부분 TODO로 하셔도 추석 처리 하셔도 괜찮을 것 같습니다.^^

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactDetailActivity.kt
> +    @Deprecated("Deprecated in Java")
onBackPressed() 함수는 현재 deprecated 되어 있습니다. deprecated를 대체할 수 있는 함수를 사용하는 것은 어떨까용?😥

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_contact_detail.xml
> +                android:scaleType="centerCrop"
해당 요소는 31 버전 이상에서만 사용되는 요소 입니다.
하지만 저희 프로젝트의 최소 타겟은 26이기 때문 만약 sdk가 26이라면 에러가 날 수 있습니다. 그렇기 때문에 
이미지 뷰의 원을 구현해주는 라이브러리 또는 cardview와 imageView를 통해서 구현 하시는 건 어떨까용?😥

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_contact_detail.xml
> +                android:text="@string/name"
String xml로 잘빼주셨군요^^👍

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_contact_detail.xml
> +                android:background="#FF7900"
backgroud color의 경우 colors 파일에 존재하는 리소스 입니다. 
colors xml의 값을 사용하는 건 어떨까용?😥
만약 컬러가 바뀌게 된다면 현재는 해당 background를 일일이 바꾸어줘야 됩니다. ㅠㅠ

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_contact_detail.xml
> +                android:textColor="#FF7900"
textColor 또한 colors xml에서 정의된 색을 사용하거나 없다면 만드는 것은 어떨까용?😥

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_contact_detail.xml
> +                app:layout_constraintHorizontal_bias="0.501"
bias의 경우 연결된 chain의 값의 기준을 잡는 요소로 현재 xml에서는 필요 없는 부분이라고 생각 합니다.😥

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_contact_detail.xml
> +                android:layout_width="285dp"
width와 height의 TextView이기 때문에 wrapcontent를 사용하는 것은 어떨까용?😥

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_contact_detail.xml
> +                android:background="#FF7900"
여기도 colors xml 파일의 값을 사용하면 좋을 것 같네용😥

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_contact_detail.xml
> +            <TextView
현재 저희 기획 처음에 메모에 대한 내용은 없었던 것으로 기억합니다.
따로 구현하시지 않으셔도 될 것 같습니다.😥

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_contact_detail.xml
> +            <EditText
현재 메모장 내용을 입력하는 부분에서 chain이 부모이고 중앙을 기준으로 잡혀있는 부분이 있어서 화면을 실행하게 되면 이력이 중앙에 쏠리게 됩니다. ㅠㅠ😥

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_contact_detail.xml
> +    <ImageButton
안드로이드 자체 backpress기능도 있기 때문에 해당 뒤로 가기 버튼의 경우는 피그마에서 했던 것처럼 srollView 내부에 상단 위에 왼쪽에 있어야 될 것 같습니다.😥

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_contact_detail.xml
> +        tools:ignore="ContentDescription,MissingConstraints" />
tools ignore를 체크하게 되면 lint 체크를 무시하게 되어 오류를 무시하게 됩니다.😥
어떤 이유에서 사용하신 건지 알 수 있을까용?

https://developer.android.com/studio/write/tool-attributes?hl=ko

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_contact_detail.xml
> +    <androidx.cardview.widget.CardView
어떤 이유에서 구현된 버튼 인지 잘 모르겠습니다. 😥
초기 피그마 명세를 따라 주세요.ㅠㅠ

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_contact_detail.xml
> +    <androidx.cardview.widget.CardView
여기도 어떤 이유의 버튼인지 잘 모르겠습니다.ㅠㅠ😥

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_contact_detail.xml
> +    <ImageButton
해당 부분의 버튼은 공통 버튼이 아닌 DetailActivity에서 꼭 구현 되어야 되는 FloatingActionButton으로 보입니다.😥

2024-04-24 12:54 UTC, yoonchanchoi commented on app/src/main/res/values/strings.xml
> +    <string name="dialog_add_name_tag">이름</string>
Strings xml로 빼주신 부분 너무 좋은 것 같습니다.👍
하지만 name -> contact_detail_name 형식으로 해당 (사용될 위치)_용도로 표시 하면 좋을 것 같습니다.😥

dialog_add의 경우는 다이얼로그 화면을 구현 하시는 연수님 페이지를 예상해서 미리 짜놓으신 것으로 보이는 지우셔도 괜찮을 것 같습니다.😁

2024-04-24 13:22 UTC, koreabgj commented on app/src/main/res/layout/activity_contact_detail.xml
> +    <androidx.cardview.widget.CardView
발제 자료 예시를 보면 메시지 버튼과 통화 버튼이 있어서 넣고 싶었습니다. 
실제 휴대폰에서 연락처 중 하나를 선택하면 통화를 누를 수 있어야 될 것 같은데.. 팀 의견 조율이 필요할 것 같습니다.

2024-04-24 13:24 UTC, koreabgj commented on app/src/main/res/layout/activity_contact_detail.xml
> +    <ImageButton
메인 액티비티와 같은 리스소를 넣는다는 의미였습니다 ^^;

2024-04-24 13:29 UTC, koreabgj commented on app/src/main/res/values/strings.xml
> +    <string name="dialog_add_name_tag">이름</string>
dialog_add는 구현 테스트를 위해서 연수님 코드에서 가져왔습니다 ^^;; 

리뷰 감사합니다!!

2024-04-24 13:54 UTC, koreabgj commented
string 파일 수정, UserInfo 마지막 콤마 삭제

2024-04-25 01:11 UTC, juseonghyun approved these changes
확인했습니다.

2024-04-25 02:37 UTC, koreabgj commented on app/src/main/res/layout/activity_contact_detail.xml
> +        tools:ignore="ContentDescription,MissingConstraints" />
alt+enter 사용시 더 주의해야 될 것 같습니다

2024-04-25 02:38 UTC, koreabgj commented on app/src/main/res/layout/activity_contact_detail.xml
> +    <androidx.cardview.widget.CardView
405f3e48ce05ba605404326e9b3f6672e33bf016

2024-04-25 02:39 UTC, koreabgj commented on app/src/main/res/layout/activity_contact_detail.xml
> +    <androidx.cardview.widget.CardView
https://github.com/juseonghyun/nbc_ContactApp/commit/405f3e48ce05ba605404326e9b3f6672e33bf016

2024-04-25 02:40 UTC, koreabgj commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactDetailActivity.kt
> +    private val userInfo by lazy {
60bc51ce43c8f0cdedec26fd85cc3ffbf895f8dd

2024-04-25 02:41 UTC, koreabgj commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactDetailActivity.kt
> +        userInfo?.let {
60bc51ce43c8f0cdedec26fd85cc3ffbf895f8dd

2024-04-25 02:43 UTC, koreabgj commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactDetailActivity.kt
> +        binding.btnFloating.setOnClickListener {
b246aa624aa62e68ea335c89b56bd4763d84882d
수정했습니다.

2024-04-25 02:45 UTC, koreabgj commented on app/src/main/res/values/strings.xml
> +    <string name="dialog_add_name_tag">이름</string>
4d8be4b07c3c59da0030188139e831be4fc5a81c
수정했습니다.

2024-04-25 02:49 UTC, koreabgj commented
수정 커밋 완료했으니 확인 부탁드립니다!

2024-04-25 02:57 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactDetailActivity.kt
> +    private val userInfo by lazy {
잘 빼주셨군요 ㅎㅎ

2024-04-25 02:58 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactDetailActivity.kt
> +        userInfo?.let {
해당 부분은 
```
userInfo?.let{

}
```
해당 부분은 원래대로 let에서 null 처리를 해주는 것이 좋아 보입니다.^^

2024-04-25 02:58 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactDetailActivity.kt
> +        binding.btnFloating.setOnClickListener {
잘 해주셨네용^^

2024-04-25 03:00 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_contact_detail.xml
> +    <androidx.cardview.widget.CardView
잘 수정해 주셨군요 ^^

2024-04-25 03:01 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_contact_detail.xml
> +    <androidx.cardview.widget.CardView
잘 수정해 주셨군요 확인 했습니다.

2024-04-25 03:02 UTC, yoonchanchoi commented on app/src/main/res/values/strings.xml
> +    <string name="dialog_add_name_tag">이름</string>
확인했습니당😀

2024-04-25 03:07 UTC, yoonchanchoi requested changes
다시 리뷰 남깁니다.
그리고 원형 이미지 뷰의 
```                
android:clipToOutline="true"
```
처리
textView의 wrap_content 처리
deprecated된 부분 처리 
userInfo의 null값 처리 부분만 다시 해서 넘겨주시면 될 것 같습니다.

2024-04-25 05:03 UTC, yoonchanchoi requested changes
리뷰 반영 확인 했습니다.
null 처리 부분은 잘 하셨습니다.^^
나머지 부분은 따로 리뷰 남겼습니다^^

2024-04-25 05:03 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactDetailActivity.kt
> +        userInfo?.let {
잘 수정해주셨네요 ㅎㅎ😀

2024-04-25 05:03 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactDetailActivity.kt
> +    @Suppress("DEPRECATION")
@suppress("DEPRECATION")은 deprecation을 해결하는 것이 아닌 오류를 무시하는 것입니다.
보통 버전 차이의 deprecation 해결하고 어쩔 수 없이 특정 버전 이하의 deprecation 코드가 들어갈 때 사용합니다.

https://stickode.tistory.com/625 참고 해보시면 좋을 것 같습니다.

2024-04-25 05:03 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_contact_detail.xml
> +                tools:targetApi="s" />
targetApi="S" 쓰게 되면 낮은 버전일 경우에는 어떻게 될까용?

https://www.google.com/search?q=%EC%9D%B4%EB%AF%B8%EC%A7%80+%EB%B7%B0+%EB%91%A5%EA%B8%80%EA%B2%8C+%EB%A7%8C%EB%93%A4%EA%B8%B0&sca_esv=8c14989faf3bda94&sxsrf=ACQVn08riHN1CgiEn3oRkQ_bFo0I5nGWRg%3A1714021100278&ei=7OIpZuvKELDI1e8P9cSDwAU&udm=&ved=0ahUKEwjr8MaWytyFAxUwZPUHHXXiAFgQ4dUDCBA&uact=5&oq=%EC%9D%B4%EB%AF%B8%EC%A7%80+%EB%B7%B0+%EB%91%A5%EA%B8%80%EA%B2%8C+%EB%A7%8C%EB%93%A4%EA%B8%B0&gs_lp=Egxnd3Mtd2l6LXNlcnAaAhgCIiHsnbTrr7jsp4Ag67ewIOuRpeq4gOqyjCDrp4zrk6TquLAyCBAAGIAEGKIEMggQABiABBiiBEjLMVD2CViPMHAIeACQAQWYAdMBoAGRHqoBBjAuMzAuMbgBA8gBAPgBAZgCEqAChQrCAgoQABiwAxjWBBhHwgIKECMYgAQYJxiKBcICCxAAGIAEGLEDGIMBwgILEC4YgAQYsQMYgwHCAgUQABiABMICBBAAGAPCAhEQLhiABBixAxjRAxiDARjHAcICChAAGIAEGEMYigXCAggQABiABBixA8ICCBAuGIAEGLEDwgIQEAAYgAQYsQMYgwEYRhj_AcICHBAAGIAEGLEDGIMBGEYY_wEYlwUYjAUY3QTYAQHCAggQABiABBiLA8ICBBAAGB7CAgYQABgKGB7CAgYQABgFGB7CAgYQABgIGB7CAggQABgIGB4YD8ICBxAhGKABGArCAgQQIRgKwgIFECEYoAGYAwCIBgGQBgq6BgYIARABGBOSBwQ3LjExoAeQqAE&sclient=gws-wiz-serp

해당 검색 창에서 참고 해 보시면 좋을 것 같아요

2024-04-25 08:28 UTC, yoonchanchoi approved these changes
내용 반영하시느라 고생하셨습니당😀

2024-04-25 08:29 UTC, merged

2024-04-30 00:32 UTC, koreabgj commented on app/src/main/java/com/example/nbc_sunnyus/model/UserInfo.kt
> +    val image: Int, // 프로필 이미지
Trailing 콤마
Trailing 콤마는 코틀린 1.4 부터 추가된 문법입니다.

class Person(
    val firstName: String,
    val lastName: String,
    val age: Int, // trailing comma
)
기존엔 저렇게 마지막 인자에 콤마를 쓸 수 없었는데, 이제 쓸 수 있죠.

https://medium.com/mj-studio/%EC%BD%94%ED%8B%80%EB%A6%B0-%EC%9D%B4%EB%A0%87%EA%B2%8C-%EC%9E%91%EC%84%B1%ED%95%98%EC%8B%9C%EB%A9%B4-%EB%90%A9%EB%8B%88%EB%8B%A4-94871a1fa646