Feature/4 콘택트리스트 구현
juseonghyun/nbc_ContactApp pull request #7
Opened 2024-04-24 03:40 UTC by juseonghyun

기능 완성

2024-04-24 03:46 UTC, koreabgj approved these changes
확인했습니다. 수고하셨습니다!

2024-04-24 05:33 UTC, hyezg approved these changes
확인했습니다!

2024-04-24 06:01 UTC, yeonsoo940630 approved these changes
확인했습니다~

2024-04-24 09:03 UTC, yoonchanchoi requested changes
구현 하시느라 고생하셨습니다. 리뷰 남깁니다. ^^

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/AndroidManifest.xml
> +        <activity
exported요소가 필요할 것 같습니다.^^

2024-04-24 09:03 UTC, yoonchanchoi commented on app/build.gradle.kts
> +    id("kotlin-parcelize")
Parcelize 설정 잘해주셨군요

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactListAdapter.kt
> +    companion object {
compainon object의 코드 컨벤션 위치가 여기가 아닌 거 같아요 😥

https://medium.com/mj-studio/%EC%BD%94%ED%8B%80%EB%A6%B0-%EC%9D%B4%EB%A0%87%EA%B2%8C-%EC%9E%91%EC%84%B1%ED%95%98%EC%8B%9C%EB%A9%B4-%EB%90%A9%EB%8B%88%EB%8B%A4-94871a1fa646
참고 링크입니다.

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactListAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder {
타입 변수에 따른 layout binding 할당을 잘 해주셧군요😀

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactListFragment.kt
> +            arguments?.getParcelable(Constants.KEY_USER, UserInfo::class.java)
데이터 값이 null일 경우에 문제가 생길 것 같습니다. null처리를 해서 null이 아닐 경우에 해주는 시는 건 어떨 까용?

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactListFragment.kt
> +        contactListAdapter.setItemClickListener(object : ContactListAdapter.OnItemClickListener {
interface를 써서 해당 아이템의 click 이벤트 아이템을 잘 처리 해주셨군요👍
추후에 interface를 밖으로 빼서 캡슐화 해주는 코드를 한번 짜보신는 것도 좋을 것 같습니다.^^

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactListFragment.kt
> +    private fun setUpData() {
해당 함수명은 데이터를 추가 하는 것과는 맞지 않은 것 같아용😥
setupData보다는 addData() 또는 데이터가 추가 되는 시점에 해당 블럭내부 코드를 쓰는 건 어떨까용?

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactListFragment.kt
> +    private fun setRecyclerView() {
어댑터 세팅을 잘해주셨군요 늦은 초기화도 잘 해주셨네용😀

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_main.xml
> +    <FrameLayout
메인 쪽 코드이기 때문에 충돌방지를 위해서 지우는 건 어떨 까용?😥

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_contact_list.xml
> +        tools:listitem="@layout/recyclerview_even" />
RecyclerView xml을 잘 구현해 주셨네용😀
하지만 정렬하는 것과 listitem을 xml에서 직접 할당하는 것도 좋지만 코드에서 할당한다면 가독성이 더 좋을 거 같아용
listitem은 나중에 한 번 해보시길 ^^

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_contact_list.xml
> +        app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
layoutManger도 코드에서 한다면 조금 더 많은 기능을 추가 할 수 있을 거 같아요
나중에 한번 해보시길 ㅎㅎ

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/res/layout/recyclerview_even.xml
> +<?xml version="1.0" encoding="utf-8"?>
전체적으로 xml 구현 잘해주셨네요👍

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/res/layout/recyclerview_even.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
정렬 한 번 해주시면 좋을 것 같아요^^

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/res/layout/recyclerview_even.xml
> +    android:layout_height="150dp">
wrap_content를 사용해서 높이는 정해서 마진과 패딩을 통해서 뷰 크기를 할당 하는 것은 어떨까요?

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/res/layout/recyclerview_even.xml
> +    <androidx.cardview.widget.CardView
카드 뷰로 잘 구현 해주셨네요👍

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/res/layout/recyclerview_even.xml
> +        android:background="#999999"
colors xml에서 함께 관리하는 것은 어떨까요?😥

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/res/layout/recyclerview_even.xml
> +<?xml version="1.0" encoding="utf-8"?>
recyclerview_even.xml의 명칭 보다는 item_(아이템요소 Ex : even)로 명칭 하는 건 어떨까용?😥

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/res/layout/recyclerview_odd.xml
> +    android:layout_height="150dp">
여기도 wrap_content으로 하시는 건 어떨까용?😅

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/res/layout/recyclerview_odd.xml
> +<?xml version="1.0" encoding="utf-8"?>
여기도 item_odd로 명칭을 바꾸는 것은 어떨까용? ^^

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/res/layout/recyclerview_odd.xml
> +        android:text="연락처1"
여기도 String xml로 빼거나 tool을 사용하는 것은 어떨까용?

2024-04-24 09:03 UTC, yoonchanchoi commented on app/src/main/res/layout/recyclerview_odd.xml
> +        android:background="#999999"
colors xml로 빼서 관리하는 건 어떨까용?

2024-04-24 15:31 UTC, juseonghyun commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactListFragment.kt
> +    private fun setUpData() {
addData와 setUpData를 분리 후 블럭 내부에서 userInfo를 lazy by 에서 lateinit var로 바꿔주고 setUpData에서 null 처리해줬습니다!

2024-04-24 15:31 UTC, juseonghyun commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactListFragment.kt
> +        contactListAdapter.setItemClickListener(object : ContactListAdapter.OnItemClickListener {
네 알겠습니다!

2024-04-24 15:31 UTC, juseonghyun commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactListFragment.kt
> +            arguments?.getParcelable(Constants.KEY_USER, UserInfo::class.java)
userInfo를 lateinit var로 늦은 초기화해준뒤
setUpData에서 null 체크를 하였습니다.
같이 해결 하였습니다. 감사합니다.

2024-04-24 15:31 UTC, juseonghyun commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactListAdapter.kt
> +    companion object {
메서드와 nested class 사이에 compainon object 위치 수정 완료했습니다!

2024-04-24 15:31 UTC, juseonghyun commented on app/src/main/AndroidManifest.xml
> +        <activity
DetailActivity를 말하시는건가요?
DetailActivity exported를 false로 명시해주었습니다!

2024-04-24 15:32 UTC, IamJuco commented on app/src/main/res/layout/recyclerview_even.xml
> +        android:background="#999999"
완료!

2024-04-24 15:32 UTC, IamJuco commented on app/src/main/res/layout/recyclerview_even.xml
> +<?xml version="1.0" encoding="utf-8"?>
Item_even
Item_odd
로 둘다 변경완료!

2024-04-24 15:32 UTC, juseonghyun commented on app/src/main/res/layout/recyclerview_even.xml
> +    android:layout_height="150dp">
wrap_content로 바꿔주고 cardView에서 margin 으로 크기 조정 하였습니다!

2024-04-24 15:33 UTC, juseonghyun commented on app/build.gradle.kts
> +    id("kotlin-parcelize")
감사합니다!

2024-04-24 15:33 UTC, juseonghyun commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactListAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder {
감사합니다!

2024-04-24 15:33 UTC, juseonghyun commented on app/src/main/java/com/example/nbc_sunnyus/ui/ContactListFragment.kt
> +    private fun setRecyclerView() {
감사합니다!

2024-04-24 15:33 UTC, juseonghyun commented on app/src/main/res/layout/activity_main.xml
> +    <FrameLayout
테스트 코드 삭제완료!

2024-04-24 15:33 UTC, juseonghyun commented on app/src/main/res/layout/fragment_contact_list.xml
> +        tools:listitem="@layout/recyclerview_even" />
넵! 나중에 한번 시도해보겠습니다!

2024-04-24 15:33 UTC, juseonghyun commented on app/src/main/res/layout/fragment_contact_list.xml
> +        app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
코드 추가 완료!

2024-04-24 15:33 UTC, IamJuco commented on app/src/main/res/layout/recyclerview_even.xml
> +<?xml version="1.0" encoding="utf-8"?>
감사합니다!

2024-04-24 15:34 UTC, IamJuco commented on app/src/main/res/layout/recyclerview_even.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
정렬 완료! 사실 이부분은 제가 항상 보기 편하게 엔터 치는데 주의하겠습니다!

2024-04-24 15:34 UTC, juseonghyun commented on app/src/main/res/layout/recyclerview_even.xml
> +    <androidx.cardview.widget.CardView
감사합니다!

2024-04-24 15:34 UTC, juseonghyun commented on app/src/main/res/layout/recyclerview_odd.xml
> +    android:layout_height="150dp">
https://github.com/juseonghyun/nbc_ContactApp/pull/7#discussion_r1578095034
이하동문

2024-04-24 15:35 UTC, juseonghyun commented on app/src/main/res/layout/recyclerview_odd.xml
> +        android:background="#999999"
https://github.com/juseonghyun/nbc_ContactApp/pull/7#discussion_r1578094132
이하동문

2024-04-24 15:36 UTC, juseonghyun commented on app/src/main/res/layout/recyclerview_odd.xml
> +        android:text="연락처1"
완료!
혹시 예외처리 throw Exception 한 부분도 strings에다가 넣어야할가요?
`else -> throw Exception("Type Error") 여기서 문자열 부분입니다.

2024-04-24 15:36 UTC, juseonghyun commented on app/src/main/res/layout/recyclerview_odd.xml
> +<?xml version="1.0" encoding="utf-8"?>
https://github.com/juseonghyun/nbc_ContactApp/pull/7#discussion_r1578094483
이하동문

2024-04-25 01:15 UTC, yoonchanchoi approved these changes
수정 다확인했습니다

2024-04-25 01:15 UTC, merged