Feature/2 다이얼로그 구현
juseonghyun/nbc_ContactApp pull request #8
Opened 2024-04-24 06:02 UTC by yeonsoo940630

다이얼로그 레이아웃 완료
저장 시 토스트메시지 띄움
저장또는 취소 시 정상적으로 종료되는것도 확인완료

2024-04-24 06:08 UTC, koreabgj approved these changes
확인했습니다. 수고하셨습니다~

2024-04-24 08:14 UTC, hyezg approved these changes
확인했습니다!

2024-04-24 08:34 UTC, koreabgj approved these changes
확인하였습니다

2024-04-24 09:21 UTC, yoonchanchoi requested changes
구현 하시느라 고생하셨습니다. 리뷰 남깁니다.^^

2024-04-24 09:21 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/DialogAdd.kt
> +package com.example.nbc_sunnyus.ui
FragmentDialog가 아니라 Dialog의 builder를 사용해서 구현 하신 부분 너무 잘 하신 것 같습니다.
저도 이렇게 할 수 있다는 것 처음 배웠습니당 ^^👍

2024-04-24 09:21 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/DialogAdd.kt
> +//interface UserInfoListener {
필요 없는 주석은 삭제하는 것이 조금 더 가독성이 좋을 것 같습니다.😥

2024-04-24 09:21 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/DialogAdd.kt
> +class DialogAdd(
DialogAdd 보다는 AddDialog를 사용하는 것은 어떨까용? 😥(해당 부분 수정 구지 않하셔도 됩니다.)

https://week-year.tistory.com/135

참고 블로그 링크 입니다. ^^

2024-04-24 09:21 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/DialogAdd.kt
> +        // 기본 버튼을 숨김
주석을 남겨 주셔서 쉽게 어떤 기능인지 알 수 있었습니다.👍

2024-04-24 09:21 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/DialogAdd.kt
> +        binding.btnSave.setOnClickListener {
Listener 부분을 따로 빼서 함수로 묶어서 호출해주는 것은 어떨까요?😥
저희가 처음 fragment에서 setupListener처럼용^^

2024-04-24 09:21 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/DialogAdd.kt
> +    private fun saveContact() {
save 해주는 부분을 함수로 빼주신 부분 너무 좋은 거 같아요👍

2024-04-24 09:21 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/DialogAdd.kt
> +        Toast.makeText(context, "연락처 추가가 완료되었습니다", Toast.LENGTH_SHORT).show()
토스트 메시지로 저장 되었을 때 알려주는 거 너무 좋은 것 같아요👍

2024-04-24 09:21 UTC, yoonchanchoi commented on app/src/main/res/drawable/round_button.xml
> +    <solid android:color="#FFB600"/> <!-- 원하는 배경색을 설정 -->
colors xml에서 따로 빼서 관리하는 건 어떨까용?😥

2024-04-24 09:21 UTC, yoonchanchoi commented on app/src/main/res/layout/dialog_add.xml
> +<?xml version="1.0" encoding="utf-8"?>
잘 구현 해주셨군요👍

2024-04-24 09:21 UTC, yoonchanchoi commented on app/src/main/res/layout/dialog_add.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
정렬 한 번 해 주시는 것은 어떨까용?😥
가독성이 증가합니다.^^

2024-04-24 09:21 UTC, yoonchanchoi commented on app/src/main/res/layout/dialog_add.xml
> +        android:hint="@string/dialog_add_name_tag"
String xml로 잘 빼주셨군요👍

2024-04-24 09:21 UTC, yoonchanchoi commented on app/src/main/res/layout/dialog_add.xml
> +    <androidx.constraintlayout.widget.Guideline
가이드 라인을 통해서 잘 중점을 잡고 layout을 구현 하셨군요👍

2024-04-24 09:21 UTC, yoonchanchoi commented on app/src/main/res/values/strings.xml
>      <string name="my_page_introduction_tag">소개</string>
String xml을 잘 구현 해주셨군요 👍

2024-04-24 09:21 UTC, yoonchanchoi commented on app/src/main/res/values/themes.xml
> +    <style name="Base.Theme.Nbc_SunnyUs" parent="Theme.AppCompat.Light">
Theme.AppCompt.Light를 사용 한다면 해당 Theme를 사용하는 모든 뷰에 상단에 ActionBar가 생길 것 같아요. 😥

2024-04-24 12:16 UTC, yeonsoo940630 commented on app/src/main/java/com/example/nbc_sunnyus/ui/DialogAdd.kt
> +        binding.btnSave.setOnClickListener {
f564bb41739be9b7c3e4223799c7a78c0c7f38ed
리스너함수 추가완료

2024-04-24 12:16 UTC, yeonsoo940630 commented on app/src/main/res/drawable/round_button.xml
> +    <solid android:color="#FFB600"/> <!-- 원하는 배경색을 설정 -->
dc9ab97c25a1c9e0d0af5b994093cfee87236bb3
수정완료

2024-04-24 12:17 UTC, yeonsoo940630 commented on app/src/main/res/values/themes.xml
> +    <style name="Base.Theme.Nbc_SunnyUs" parent="Theme.AppCompat.Light">
2697904dfe1d9bb9926760b4e6f399525b6f0084
수정완료

2024-04-24 12:18 UTC, yeonsoo940630 commented on app/src/main/res/layout/dialog_add.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
aa0095e5eebf486dc170d6074fb531c5892892c9
정렬완료

2024-04-24 12:24 UTC, koreabgj approved these changes
수고 많으셨어요~

2024-04-24 12:27 UTC, yeonsoo940630 commented on app/src/main/java/com/example/nbc_sunnyus/ui/DialogAdd.kt
> +//interface UserInfoListener {
삭제완료

2024-04-24 12:27 UTC, yeonsoo940630 commented on app/src/main/java/com/example/nbc_sunnyus/ui/DialogAdd.kt
> +class DialogAdd(
넵 참고사이트까지 감사합니다

2024-04-25 01:11 UTC, juseonghyun approved these changes
확인했습니다.

2024-04-25 01:57 UTC, yoonchanchoi approved these changes
수정하시느라 고생하셨습니당

2024-04-25 01:57 UTC, merged

2024-04-25 02:55 UTC, koreabgj reviewed
확인했습니다