Feature/3 메인페이지 구현
juseonghyun/nbc_ContactApp pull request #9
Opened 2024-04-24 08:51 UTC by hyezg

### ✏️ 개요

메인페이지 구현 (4/22~4/24) 

### 💻 작업 사항

플러팅 버튼, 탭 레이아웃 설정, 뷰페이져어뎁터 생성

### 📄 리뷰 노트

#### ViewPager2
메인 레이아웃에 뷰페이져2를 넣고 뷰페이져어뎁터를 생성했습니다. 
어뎁터 부분에서 `createFragment` 를 만들어 `position`에 따라 프레그먼트가 보이도록 설정하였습니다.

#### TabLayout
메인 레이아웃의 하단바를 `TabLayout`을 이용했고, MainActivity에서 `arrayOf()`로 탭 목록을 만들었습니다. 그리고 탭의 `position`에 따라 각각 icon을  `getDrawable()`을 활용해 만들어줬습니다. 탭을 눌렀을 때의 글씨를 레이아웃에서 `tabSelectedTextColor` 를 이용해 흰색으로 지정해줬습니다.

#### Floating Action Button
플러팅 버튼은 theme의 style을 Circle로 설정해서 메인 레이아웃에 `shapeAppearanceOverlay` 을 사용해 플러팅 버튼에만 적용되도록 하였습니다.

### 📱결과물
<img alt="image" src="https://github.com/juseonghyun/nbc_ContactApp/assets/112006114/e0b1e7fa-12e5-45f1-a4cf-c08e26c294ca" width="40%" >

2024-04-24 09:03 UTC, koreabgj approved these changes
수고 많으셨습니다!

2024-04-24 09:41 UTC, yoonchanchoi requested changes
구현 하시느라 고생하셨습니다.

2024-04-24 09:41 UTC, yoonchanchoi commented on app/src/main/AndroidManifest.xml
> +            android:theme="@style/Base.Theme.Nbc_SunnyUs">
Theme에서 
```    
<style name="Base.Theme.Nbc_SunnyUs" parent="Theme.Material3.DayNight.NoActionBar">
    </style>

    <style name="Theme.Nbc_SunnyUs" parent="Base.Theme.Nbc_SunnyUs" />
``` 

으로 사용하신다면  메인에서 따로 기본 테마를 설정 하실 필요 없을 것 같아요😥
확인해주세요^^

2024-04-24 09:41 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/MainActivity.kt
> -    private val binding : ActivityMainBinding by lazy {
by lazy로 늦은 초기화 잘 해주셨네요 ^^👍

2024-04-24 09:41 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/MainActivity.kt
> +        binding.apply {
when 절을 통해서 코드에 맞게 잘 구현해주셨군요👍

2024-04-24 09:41 UTC, yoonchanchoi commented on app/src/main/java/com/example/nbc_sunnyus/ui/ViewPager2Adapter.kt
> +private const val NUM_TABS = 2
company object로 관리하는 것은 어떨까용?

2024-04-24 09:41 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/floatingbtn_main"
명칭이 너무 긴 것 같다면 fab 등으로 사용하시는 건 어떨까용?

2024-04-24 09:41 UTC, yoonchanchoi commented on app/src/main/res/layout/activity_main.xml
> +        app:tabSelectedTextColor="@color/white"
선택된 상태에 따른 색 변환 잘 해주셨네요^^

2024-04-24 09:57 UTC, yeonsoo940630 reviewed
확인했습니다~

2024-04-24 09:58 UTC, yeonsoo940630 approved these changes
확인했습니다~

2024-04-24 11:04 UTC, hyezg commented on app/src/main/AndroidManifest.xml
> +            android:theme="@style/Base.Theme.Nbc_SunnyUs">
넵!

2024-04-24 11:11 UTC, hyezg commented on app/src/main/java/com/example/nbc_sunnyus/ui/ViewPager2Adapter.kt
> +private const val NUM_TABS = 2
넵!

2024-04-24 11:34 UTC, koreabgj approved these changes
확인하였습니다!

2024-04-25 01:11 UTC, juseonghyun approved these changes
확인했습니다.

2024-04-25 01:48 UTC, yoonchanchoi approved these changes
수정하느라 고생하셨습니다.

2024-04-25 01:51 UTC, merged